CREATE TABLE IF NOT EXISTS tasks (
  id       INT AUTO_INCREMENT PRIMARY KEY,
  title    VARCHAR(255) NOT NULL,
  done     TINYINT(1)   NOT NULL DEFAULT 0,
  priority ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'low',
  dueDate  VARCHAR(20)  DEFAULT '',
  image    VARCHAR(500) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS migrations (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  hash       VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);